
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";

import { NextIntlClientProvider, useMessages } from "next-intl";
import ChangeLanguage from "./component/switchLanguage";

const font = Poppins({ subsets: ["latin"], weight:"400" });

export const metadata: Metadata = {
  title: "IEI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params : {locale}
}: Readonly<{
  children: React.ReactNode;
  params : {locale : string}
}>) {

  const msg = useMessages()

  return (
    <NextIntlClientProvider locale={locale} messages={msg}>
      <html lang={locale} className="overflow-x-hidden">
        <body className={font.className}>
          {children}
          <ToastContainer/>
          <ChangeLanguage/>
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
